#+TITLE: Enable JetBrains Mono Ligatures
#+DESCRIPTION: Configuración de ligaduras en spacemacs
#+AUTHOR: Sergio Benítez
#+DATE:<2020-12-23 mié>
#+HUGO_BASE_DIR: ~/Development/suabochica-blog/
#+HUGO_SECTION: /post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

Desde hace unos años las fuentes de codificación empezaron a agregar ligaduras relativas a sintaxís comunes en diferentes lenguajes de programación. En esta publicación se va a compartir una configuración para habilitar el uso de ligaduras en spacemacs. Antes de comenzar, es importante aclarar qué es una ligadura.

* PROJ Qué son las ligaduras?

En escritura y tipografía, la ligadura (ligature en inglés) ocurre cuando dos o más grafemas o letras se unen para formar un solo glifo. Ejemplos son los caracteres æ y œ utilizados en inglés y francés, en los que las letras 'a' y 'e' se unen para la primera ligadura y las letras 'o' y 'e' se unen para la segunda ligadura.

#+BEGIN_QUOTE
Tenga en cuenta que agregar ligaduras a una fuente de codificación no cambia su código de ninguna manera, solo cambia la forma en que se muestra.
#+END_QUOTE

Hoy en día se puede encontrar una gran variedad de fuentes con ligaduras. En la siguiente lista se muestran la fuentes más populares según el sitio web better web type:

- Fira code
- Iosevka
- Monoid
- Hasklig


* Configuración de ligatures

Hay muchos caminos para lograr que una fuente con ligadures sea visualizada,
desde la instalación de paquetes en MELPA como pretty-mode hasta configuraciones
puntuales en el .dotspacemacs files. La solución efectiva para mi caso fue el
uso de reglas de composición como se muestra a continuación:

#+begin_src elisp
(defconst jetbrains-ligature-mode--ligatures
   '("-->" "//" "/**" "/*" "*/" "<!--" ":=" "->>" "<<-" "->" "<-"
     "<=>" "==" "!=" "<=" ">=" "=:=" "!==" "&&" "||" "..." ".."
     "|||" "///" "&&&" "===" "++" "--" "=>" "|>" "<|" "||>" "<||"
     "|||>" "<|||" ">>" "<<" "::=" "|]" "[|" "{|" "|}"
     "[<" ">]" ":?>" ":?" "/=" "[||]" "!!" "?:" "?." "::"
     "+++" "??" "###" "##" ":::" "####" ".?" "?=" "=!=" "<|>"
     "<:" ":<" ":>" ">:" "<>" "***" ";;" "/==" ".=" ".-" "__"
     "=/=" "<-<" "<<<" ">>>" "<=<" "<<=" "<==" "<==>" "==>" "=>>"
     ">=>" ">>=" ">>-" ">-" "<~>" "-<" "-<<" "=<<" "---" "<-|"
     "<=|" "/\\" "\\/" "|=>" "|~>" "<~~" "<~" "~~" "~~>" "~>"
     "<$>" "<$" "$>" "<+>" "<+" "+>" "<*>" "<*" "*>" "</>" "</" "/>"
     "<->" "..<" "~=" "~-" "-~" "~@" "^=" "-|" "_|_" "|-" "||-"
     "|=" "||=" "#{" "#[" "]#" "#(" "#?" "#_" "#_(" "#:" "#!" "#="
     "&=")
)

(dolist (pat jetbrains-ligature-mode--ligatures)
  (set-char-table-range composition-function-table
    (aref pat 0)
    (nconc (char-table-range composition-function-table (aref pat 0))
      (list (vector (regexp-quote pat) 0 'compose-gstring-for-graphic))
    )
  )
)
#+end_src

* Referencia
- [[https://emacs.stackexchange.com/questions/55059/ligatures-with-the-jetbrains-mono-font][Ligatures with the JetBrains Mono font]]
- [[https://betterwebtype.com/5-free-monospaced-fonts-with-coding-ligatures/][5 free monospaced fonts with coding ligatures]]
