baseurl = "/"
title = "Suabochica's Blog"
theme = "harbor"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Suabochica"
    description = "Code like a writer"
    github = "https://github.com/suabochica"
    twitter = "https://twitter.com/suabochica"
    email = "info@suabochica.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"