baseurl = "http://suabochica.local"
title = "Sua Bochica"
theme = "m10c"
paginate = 12

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Sergio Benítez"
  description = "Code like a writer"
  avatar = "/sua_profile.jpg"
  favicon = "/favicon.ico"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/suabochica"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/suabochica"
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/suabochica"
