baseurl = "https://blog.suabochica.com"
title = "Blog de suabochica"
theme = "m10c"
paginate = 12

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags"

[params]
  author = "Sergio Benítez"
  description = "Desarrollador Full-Stack con más de 10 años de experiencia."
  avatar = "/sua_profile.jpg"
  favicon = "/favicon.ico"
  menu_item_separator = " - "
  [[params.social]]
    name = "porfolio"
    url = "https://suabochica.com"
  [[params.social]]
    name = "github"
    url = "https://github.com/suabochica"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/suabochica"
  [[params.social]]
    name = "instagram"
    url = "https://instagram.com/suabochica"

[params.style]
  darkestColor = "#3c3836"
  darkColor = "#282828"
  lightColor = "#fbf1c7"
  lightestColor = "#689d6a"
  primaryColor = "#d65d0e"
