#+TITLE: Activos Digitales
#+DESCRIPTION: Serie que recopila una aprendizaje sobre blockchain
#+AUTHOR: Sergio Benítez
#+DATE:<2021-11-24 Wed>
#+STARTUP: fold
#+HUGO_BASE_DIR: ~/Development/suabochica-blog/
#+HUGO_SECTION: /post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

A lo largo de esta publicación, se trabajará con activos digitales de manera programática utilizando su terminal y JavaScript. Esto está destinado a ayudarlo a prepararse para el próximo proyecto en el que utilizará estas habilidades en su propia cadena de bloques privada.

También se familiarizará con algunas ideas sobre cómo exponer sus funcionalidades Blockchain a sus clientes usando RESTApi's.

* Activos Digitales

* Codificar y Decodificar
En esta sección se dará el primer paso para unificar los activos digitales con el Blockchain. Como se comentó anteriormente, los activos digitales son codificados y decodificados para facilitar la comunicacíon ente computadores y personas. Para ellos se va a empezar con la codificación y decodificación de texto e imágenes.

#+begin_notes
Codificar: Proceso para poner una secuencia de caracteres en un formato especializado para una transmisión o almacenamiento eficiente en computadores.
#+end_notes

#+begin_notes
Decodificar: Tomar archivos codificados, sin procesar e ilegibles y los convierte de nuevo a un formato legible para humanos
#+end_notes

** Tipos de codificación y decodificación

- ASCII: American Standar Code for Information Interchange
- Hexadecimal: Representación concisa de binarios para que sea más legible por humanos
- Base64: Esquema de codificación destinado a representar datos como números en un formato de cadena

** Demostración
Hasta este punto se ha repasado la teoría detrás de los activos digitales, codificación y decodificación. Ahora es tiempo de poner este conocimiento en práctica, y para ello se va a utilizar la terminal del sistema operativo en los siguientes casos:

- Codificar y decodificar *texto* dentro de la terminal
- Codificar y decodificar *archivos de texto* desde la terminal
- Codificar y decodificar *archivos de imágenes* desde la terminal
