#+TITLE: Cadena de Suministro
#+DESCRIPTION: Serie que recopila una aprendizaje sobre blockchain
#+AUTHOR: Sergio Benítez
#+DATE:<2021-12-11 Sat>
#+STARTUP: fold
#+HUGO_BASE_DIR: ~/Development/suabochica-blog/
#+HUGO_SECTION: /post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

Para entender la arquitectura establecida en Blockchain se debe tener conocimientos de su cadena de suministro y así plantear soluciones más adecuadas.

La cedena de suministro es un tema muy amplio ya que contempla muchos aspectos en cualquier negocio. En general incluye todo lo necesario para ejecutar los siguientes pasos en un producto:

- Planificar
- Construir
- Crear
- Manufacturar
- Entragar

En resumen, la cadena de suministro abarca todo lo que necesita el producto de una compañia, desde los insumos originales hasta el producto final teniendo como intermediario el proceso de ventas. Su objetivo es ejecutar todo este proceso de la manera más efectiva posible.

Como desarrolladores de cadena de bloques, hay interés en atender las cadenas de suministro porque en el núcleo de cada una de las transacciones hay dos puntos principales:

1. Confianza
2. Automatización

Estos puntos pueden ser hechos con la creación de un libro mayor abierto y compartido que permita a las empresas a colaborar e interactuar de manera más efectiva.

Como se puede observar, el Blockchain tiene un impacto enorme si se resuelva la forma de cómo los contratos inteligentes puede mejorar las cadenas de suministro.

Esto ya está comenzando a gran escala. A principios de 2018, Maersk, la empresa de transporte de contenedores más grande del mundo, e IBM se asociaron para crear TradeLens, una plataforma para construir estándares abiertos para aplicar blockchain a la cadena de suministro global del mundo.

TradeLens utiliza la tecnología IBM Blockchain como base para las cadenas de suministro digitales, lo que permite que varios socios comerciales colaboren estableciendo una vista única compartida de una transacción sin comprometer los detalles y la privacidad.

Maersk e IBM fueron los primeros en unirse a TradeLens, pero más de 90 organizaciones de todo el mundo se han unido para participar en la plataforma TradeLens.

* TODO Descriprción General de la Arquitectura Blockchain 

** Web 2.0

** Web 3.0 

* TODO UML

** TODO Diagramas de Actividad

** TODO Diagramas de Secuencia

** TODO Diagramas de Estado


* TODO Modelando Datos

* TODO Decisiones en la Capa de Servicios

* Recapitulación

En esta publicación se discutió la arquitectura de una cadena de bloques para luego planificar y diseñar una solución Blockchain.

El enfoque partió de la evolución de la web desde la web 1.0 hacia la web 2.0, culimando en la web 3.0 resalanto los cambios de arquitectura que debieron presentarse para avanzaz de una versión a otra.

Con dichas bases en temas de arquitectura, se indago en una etapa de planificación a través de UML para modelar las actividades, las secuencias y los cambios de estado de una tienda de mascotas.

Usando la información de la etapa de planificación, se creo un diagrama para modelar los datos para redactar las relaciones entre los contratos inteligentes que se están construyendo.

Por último, se agruparon las preguntas relevantes para soluciones de plataforma y bases de datos teniendo en cuenta los criterios: red, rendimiento, lógica de negocio y consenso.
