#+TITLE: La Revolución Blockchain
#+DESCRIPTION: Serie que recopila una aprendizaje sobre blockchain
#+AUTHOR: Sergio Benítez
#+DATE:<2021-10-25 Thu> 
#+STARTUP: fold
#+HUGO_BASE_DIR: ~/Development/suabochica-blog/
#+HUGO_SECTION: /post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

La cadena de bloques (mejor blockchain) se ha descrito como todo, desde oro digital hasta un reemplazo de Internet.

Este campo se está desarrollando increíblemente rápido y hay muchas oportunidades en las que puede participar.

La blockchain tiene el potencial de revolucionar industrias como las finanzas, el gobierno y la medicina. Incluso está reimaginando la forma en que pensamos sobre la identidad y la seguridad personal.

* ¿Por qué Blockchain?
 
Trabajar en el espacio de Blockchain hoy en día es muy llamativo ya que básicamente esta reinventado el Wall Street. Con Blockchain se esta automatizando todo lo que se hace en la bolsa de valores y se esta tranformando en código. En otras palabras el Blockchain está construyendo una economía digital.

Es emocionante ver como todo este concepto se inicia ya que puede equipararse con el hecho de haber nacido hace 20 o 30 años en la era del Internet y ser testigo de como este cambio hizo que la información se volviera digitalizada y programable.

Ciertamente, desarrollar una nueva Blockchain es retador, ya que requiere de conocimiento de varios temas y es una tarea díficil para cualquier programador. Paralelamente, la demanda de posiciones abiertas para trabajos con Blockchain ha venido incrementando en los últimos años, no obstante, la oferta sigue siendo limitada porque es un campo que se ha venido acercando sigilosamente a la gente con una estrucura demasiado amplia, si se compara con aprendizajes web.

* La Influencia del Blockchain

El Blockchain está cambiando las industrias en todo el mundo a tráves de las siguientes industrias: identificación personal, medicina, finanzas, gestión de cadenas de suministros y gobierno. Ahora bien ¿cómo Blockchain hace esto posible?.

Básicamente, Blockchain es una nueva forma de compartir datos que permite realizar transacciones de forma más segura, más transparente y más barata que antes. Todo esto se puede lograr sin que grandes compañias collecionen y administren nuestra información como lo hacen hoy en dia. 

Por ejemplo, para la industria de identificación personal todos queremos que nuestra identidad sea segura. Nadie debería estar en capacidad de acceder a la información sobre los lugares a donde vamos, que estamos haciendo o incluso que estamos planificando sin nuestro permiso. El problema es que hoy en día estamos otorgando esta información a las grandes corporaciones a cambio de los servicios que ellos proveen. Este escenario nos expone a perder el control sobre como nuestra información esta siendo usada.

Dichas corporaciones almacenan los datos que nosotros producimos en grandes bases de datos centralizadas, teniendo información tan importante en una única ubicación, que en primera instancia podía ser de utilidad, pero nos exhibe a algunos riesgos, como por ejemplo los ataques de hacker para el robo de datos. Un caso reciente fue en 2017 con Equifax, en donde aproximadamente 140 millones de personas perdió información importante de accesos a tarjetas de creditos y cuentas bancarias gracias a un ataque de hackers. 

El punto a favor de Blockchain para mitigar este riesgo se debe a que los datos no se mantienen en una base de datos centralizada, puesto que es compartida por cada una de las personas verificadas que están en la red. Además, la información es asegurada usando cifrados para que los criminales no puedan robar los datos, haciendo así que este tipo de violación de datos sea casi imposible.

Otro campo de acción del Blockchain es la gestión de cadenas de suministros en diferentes mercados. Por ejemplo en la industria automotriz para construir un carro hay muchas compañias involucradas. Las piezas de envío como tornillos, paneles, motores o puertas son suministrados por diferentes proveedores y es conveniente realizar un seguimiento sobre dichas partes. Aún cuando el carro ya esta construido, se debe tener un rastreo de cuando llega al fabricante, se pasa al distribuidor y lo obtiene el cliente final. Actualmente, crear esta cadena de suminstro es extremadamente complicada, porque la información esta regada por muchas compañias que incluso llegan a tener políticas para no compartir la información, convirtiendo en una lucha la manutención de datos actualizados. Por lo tanto, las compañias se ven obligadas a gastar recursos para el manejo de dichos registros.

Con Blockchain, la información del carro sería pública y estaría disponible en cualquier momento, permitiendo así conocer la información exacta de los detalles y el historial de cada una de las partes de productos que se compran, se alquila o se usen. Ahora bien ¿qué pasaría si nadie quisiera compoartir la información con los demás? No hay problema ya que en Blockchain la información pública también es anónima. De esta forma, nadie podrá saber que es lo que usted está haciendo. También se tienen otras medidas de seguridad constuidas en el sistema que serán discutidas más adelante.

Concluyendo de manera rapida la influencia de Blockchain en las diferentes industrias se tiene para medicina la oportunidad de salvar más vidas con información más segura y precisa del paciente. También es posible envíar dinero a todos el mundo de manera gratuita y segura cambiando de manera potencial el sistema finaciero. Por último las elecciones gubernamentales podrían realizarse de una manera segura y transparente sobre el Blockchain.

* Visión General de Blockchain

Cada día la popularidad del Blockchain sigue creciendo pero en escencia ¿qué son los Blockchains? ¿cómo	funcionan? y ¿qué problemas solucionan? Una definición de Blockchain puede ser la siguiente:

#+begin_src quote
Blockchain es una base de datos compartida que contiene una lista de transacciones. Dichas transacciones son hecha por usuarios que son parte de la red de cadenas de bloques.
#+end_src

Con esta definición en mente, se puede establecer como una transacción algo tan simple como el envío de dinero. De hecho, este es quizas el caso de uso más popular de Blockchain establecido por la criptomoneda Bitcoin. La idea de Bitcoin vino de un desarrollador desconocido bajo el alias de Satoshi Nakamoto en 2009 con el propósito de crear una nuevo tipo de moneda que esta abierta a cualquier persona para establecer la confianza necesaria para facilitar las tranasacciones.

El Blockchain es llamativo por su forma de crear, organizar y gestionar datos ya que favorece escenarios y nuevas alternativas a problemas actuales. En principio, los datos en el Blockchain son compartidos por todos los usuarios en la red. Lo que significa que los datos no estan en manos de una autoridad centralizada. Por otra parte, es extremadamente díficil cambiar cualquier dato cuando es puesto en el Blockchain. Al combinar estas dos características se obtiene un historial de transacciones permanente compartido en la cual todos los miembros de la red pueden confiar en que es precisa y actualizada.

Ahora bien ¿Cómo funciona el Blockchain? Las entidades relevantes en el Blockchain son: Un emisor, un receptor y una transacción. La transacción es un registro de información que el emisor envía al receptor. Para el ejemple del envío de dinero, la información de la transacción sería la cantidad de dinero que se envia. Una vez la transacción esta hecha, es enviada a una red de usuarios. El objetivo de esta red de usuarios es tomar nuestras transacciones y agruparlas con otras en un bloque. Cuando una cantidad importante de transacciones sean recolectadas, el bloque se completa y esta listo para ser agregado de manera permanente al Blockchain. Para asegurar su permanencia, al bloque se le asigna un valor único conocido como Hash. Este sería la huella digital de bloque y con ello se podrá identificar el bloque en el futuro. El Hash es sumamente importante ya que también ayuda a identificar cuales son los datos que están en el bloque.

Al actualizar la información de la transacción, como por ejemplo reducir la cantidad de dinero enviada, el Hash será cambiado y se crea un nuevo bloque haciendo invalido el bloque antiguo. No obstante, ambos bloque se unirán y con el tiempo se continuará con la creación de cadenas de bloques cada vez más largas. El resultado es una cadena de bloques con registros históricos de transacciones cuya información no puede ser modificada y sucedieron en una red de usuarios. 

* Motivación del Blockchain

Si bien Blockchain tiene sus raíces en las finanzas, sus aplicaciones van mucho más allá. Quizas su característica más llamativa es su naturaleza disruptiva en todos los verticales de las tecnologías de información. Es emocionante saber que hoy en día se pueden hacer transacciones con cualquier persona en cualquier lugar del mundo a través de una red confiable. El otro aspecto llamativo es la anulación de intermediarios en las transacciones. Evidentemente esto fomenta intercambios y procesos más transparentes que pueden reflejarse en campos gubernamentales e incluso en la mejora de los registros médicos electrónicos de los datos de un paciente.

En escencia, los más emocionante de Blockchain es simplemente su capacidad de derribar las paredes sin tener que preocuparse por las fronteras cuando se trata de realizar transacciones con varias comunidades. Es importante aclarar que Blockchain no es solo las transacciones. Las tecnologías que hacen que esas transacciones funcionen y el tipo de datos que se pueden embuir en dichas transacciones es un hecho maravilloso por la flexibilidad que nos ofrece por solo usar a nuestro favor la tecnología como tal.

