#+TITLE: Gestión de Transacciones Blockcahin
#+DESCRIPTION: Serie que recopila una aprendizaje sobre blockchain
#+AUTHOR: Sergio Benítez
#+DATE:<2021-11-10 Wed> 
#+STARTUP: fold
#+HUGO_BASE_DIR: ~/Development/suabochica-blog/
#+HUGO_SECTION: /post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

Los Blockchains son sistemas basados en transacciones, por lo tanto el tema de transacciones es uno de los más importantes.

En esta publicación se van a revisar de manera conjunta los conceptos que se mencionaron en los [[fundamentos de blockchain][./2021-10-27-fundamentos-de-blockchain.org]] de llaves, bloques, billeteras, entre otros. El próposito de este árticulo es atacar los siguientes puntos:

- Entender las mecánicas de una transacción simple entre dos entidades, usando llaves privadas, llaves públicas, billeteras y un blockchain público.
- Determinar y generar el tipo de billetera adecuado segun las necesidades de la situación (No determinística, Determinista Secuencial, Determinista Jerárquica).
- Crear y restaurar una billetera bitcoin usando llaves privadas.
- Reconocer la firma de transacciones como parte del ciclo de vida de la transacción y describir tanto su propósito como su proceso.

* Identitdad Blockchain


Así como un número de seguridad social, una cuenta bancaria o una licencia de conducción, la identidad blockchain es como se establece usted mismo en el mundo de la cadena de bloques. Para revisar el cómo se maneja identidad en blockchain se van a revisar dos casos. El primero es describir como una persona que posee dinero tiene acceso para gastarlo garantizando que su transacción no puede ser rastreada. 

* Billeteras

** Tipos de Billeteras

   - Billeteras no determinísticas
   - Billeteras determinísticas
   - Billeteras jerarquicas determinísticas

* Llaves Privadas

* Obtengas su Propia Billetera
  
* Restaurando la Identidad en Blockchain

* Señal de Transacción

* Ciclo de Vida de una Transacción en Blockchain

