#+TITLE: Datos en Blockchain
#+DESCRIPTION: Serie que recopila una aprendizaje sobre blockchain
#+AUTHOR: Sergio Benítez
#+DATE:<2021-11-17 Wed> 
#+STARTUP: fold
#+HUGO_BASE_DIR: ~/Development/suabochica-blog/
#+HUGO_SECTION: /post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

En esta publicación se usará Bitcoin Core para explorar las limitaciones y las mejores prácticas al incorporar datos en transacciones de blockchain.

Los propósitos puntuales de esta sección son:
- Reconocer la estructura de datos de bloques y transacciones.
- Reconocer el propósito de los códigos de operación de Bitcoin Script que se usan comúnmente en las partes de entrada y salida de un proceso de transacción.
- Explore las limitaciones y las mejores prácticas para incorporar datos en transacciones de blockchain. 

¡Usar estas habilidades lo ayudará con la con la construcción de los componentes de su propia cadena de bloques simple y privada desde cero!

* Modelos de datos en Blockchain

Para entender como la información es almacenada en cualquier blockchain, es necesario aclarar los modelos de datos del bloque y la transacción. Anteriormente se menciono que el modelo de dato de un bloque se comopone de:

- Un encabezado
- Un cuerpo

El encabezado de bloque almacena la siguiente información:

- *Hash del bloque anterior:* el valor hash del bloque que viene directamente antes de un bloque determinado en la cadena. Esto es lo que une los bloques en el blockchain
- *Hora:* la hora en que se creó el bloque también se mantiene en el encabezado.
- *Raíz de Merkle:* la raíz de Merkle es un hash que representa cada transacción incluida dentro del bloque. Para obtener la raíz de merkle, los pares de transacciones dentro de un bloque se mezclan repetidamente. Cada par da como resultado un solo hash. Luego, el hash de dos pares de transacciones se vuelve a mezclar con otros dos pares hash, una y otra vez hasta que se llega a un solo valor hash, el cuál sería la raíz del árbol. Con ese valor hash final, conocido como raíz merkle, se pueden buscar las transacciones originales o los valores hash que las crearon incluyendo los primeros bloques del blockchain.
- *Nonce:* un nonce (significa "número que solo se usa una vez") es un número que se usa en la minería de bitcoin. Los mineros de la cadena de bloques están resolviendo el nonce que, cuando se agrega a un bloque con hash, y esos 2 valores se repiten, resolverán el rompecabezas de la minería.

Por otra parte, el cuerpo del bloque se encarga de las transacciones, incluyendo las entradas y las salidas de las mismas. en la siguiente sección se expandirá el modelo de datos de las transacciones haciendo enfásis en la entradas y las salidas ya que su relación permite el entendimiento de la creación de transacciones propias. No importa que blockchain este trabajando, recuerde que las cadenas de bloques son sistemas transaccionales.

* TODO Transacciones

** Entrada y Salidas

** Modelo de Datos en las Transacciones

* TODO Scripts de Bitcoin

  - *Versión:*
  - *Conteo de entradas:*
  - *Hash de la salida previa:*
  - *Índice de la salida previa:*
  - *Tamaño del script de desbloqueo:*
  - *Script de desbloqueo:*
  - *Conteo de salidas:*
  - *Cantidad:*
  - *Tamaño del script de bloqueo:*
  - *Script de bloqueo:*
  - *Tiempo de bloqueo:*

** Opcodes 

** Atributos de un Script

* TODO Ciclo de Vida de una Transacción en Blockchain

* TODO Incrustar datos en el Blockchain
