#+TITLE: Herramientas de JavaScript
#+DESCRIPTION: Serie que recopila una descripción general de React
#+AUTHOR: Sergio Benítez
#+DATE:<2021-03-15 Thu> 
#+STARTUP: fold
#+HUGO_BASE_DIR: ~/Development/suabochica-blog/
#+HUGO_SECTION: /post
#+HUGO_WEIGHT: auto
#+HUGO_AUTO_SET_LASTMOD: t

Es tiempo de indagar sobre la diferentes herramientas que permiten crear un ambiente de desarrollo para aplicaciones web React:

## npm

~npm~ no significa Node Package Manager, pero si es un administrador de paquetes para NodeJS. ~npm~ se ha compertido en el gestor de paquetes del campo frontend y cuenta con una herramienta de líneas de comando llamada ~npm~ también. ~npm~ permite traer código desde el registro de ~npm~ en donde se almacenan una cantidad consideraple de módulos de código abierto que la gente ha escrito y que cualquiier desarrollador puede utilizar. Al correr el siguiente comando:

#+begin_src zsh
npm install react
#+end_src

Se va a obtener la última versión de React guardada en el registro de npm. Para crear un proyecto ~npm~ se ejecuta el siguiente comando en el directorio raíz del proyecto:

#+begin_src zsh
npm init -y
#+end_src

El requisito es tener instalado NodeJS. Una vez ejecutado el comando se creará un archivo ~package.json~ el cual se va a modificar más adelante. Este archivo permite instalar y salvar paquetes.

## Prettier

Es importante mantener una calidad alta cuando se escribe código, o por lo menos, aceptar como compañeros de trabajo a la combinación ESLint y Prettier. La mayoría de los desarrolladores somos perezosos y siempre estamos en la búsqueda de recargar varias responsabilidades a la máquina para tener el foco en tareas de arquitectura y resolución de problemas, invertiendo la menor cantidad de tiempo posible en contextos de sintáxis y estilo de código. Hay muchas herramientas que nos ayudan a mantener la calidad del código alta, pero ESLint y Prettier son quizas la más populares en el flujo de trabajo de aplicaciones web.

Prettier es una herramienta increible, ya que su creador estaba hastiado de lidiar con problemas de estilo de código: donde colocar sangrías, cuando usar saltos de línea, entre otros.Prettier toma el código que se escribe, lo descompone en un árbol de sintaxis abstracta (AST) que es solo una representación de su código. Luego toma ese AST, desecha todo el estilo de código que creó y lo vuelve a imprimir usando un estilo predefinido. Si bien esto suena un poco aterrador, el resultado es genial. Al perder el control del estilo de su código, ya no tiene que pensar en ello. Su código siempre es coherente, al igual que el código del resto de su equipo.

Una analogía valida es si tu cerebro es un procesador, puedes liberar el hilo de tu cerebro que se preocupa por los estilos de código y la legibilidad: simplemente te sucede a ti. ¿No te gustan los puntos y comas? ¡No las escribas! Los pone por ti. Punto para Prettier.

Para instalar Prettier se ejecuta el siguiente comando:

#+begin_src zsh
npm install -D prettier
#+end_src

Ahora se crea el archivo ~.prettierrc~. En este archivo se van a definir las configuraciones que se quieren aplicar sobre determinado formato de archivo. Prettier ofrece reglas de estilo de código para JavaScript, TypeScrip, JSX, entre otros. Las (opciones)[https://prettier.io/docs/en/options.html] que ofrece Prettier de configuración son varias, ya que van desde el ancho de impresión, hasta el ancho del Tab. Por ahora se va a dejar una configuración vacía para el archivo ~.prettierrc~:

#+begin_src js
// .prettierrc
{}
#+end_src

Prettier funciona de maravilla con Visual Studio Code. La recomendación es instalar la (extensión)[https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode&WT.mc_id=reactintro-github-brholt] y configurarla para que que Prettier solo se ejecuto cuando detecte un archivo ~.prettierrc~. Para ello, hay que buscar dentro del archivo de configuración de la extensión la opción ~prettier.requireConfig~ y definirla como ~true~. Si se quiere dar formato al archivo cuando se guarde, se debe definir la opción ~editor.formatOnSave~ con ~true~

Puede ser algo incómodo tratar the recordar todos los comandos CLI que se puede correr en el proyecto, Dichos comandos pueden etiquetarse en la sección "scripts" del  ~package.json~. Por ejemplo, el comando para dar formato a los archivo ~.js~ y ~.jsx~ sería:

#+begin_src js
// package.json
{
    "scripts": {
        "format": "prettier --write \"src/**/*.{.js, .jsx}"
    }
}
#+end_src

Ahora se puede ejecutar el siguiente comando:

#+begin_src zsh
npm run format
#+end_src

Con esta configuración ya no es necesario recordar la cantidad de comandos que se pueden ejecutar para darle formato al código. Sobra la marcha se aprenderá mas de las funcionalidaes de Prettier.

## ESLint

Ya se vio que Prettier soluciona todo lo realtivo al formato de código. Ahora bien, es posible forzar algunos estilos de código relacionados a uso. Por ejemplo, usted quiere forzar a que el equipo  nunca utilice la palabra reservada ~with~ de JavaScript, ya que no se considera una buena práctica en JavaScript. ESLint entra en este contexto ya que ayuda a resolver dichos contextos.

El primer paso es instalar ESLint a través de ~npm~ con sus respectivas dependencias:

#+begin_src zsh
npm install -D eslint eslint-config-prettire
#+end_src

Una vez instalado, se procede con la configuración del linter. Actualmente hay docenas de configuraciones preestablecidas para ESLint y puede usar cualquiera de ellas. La configuración de Airbnb es muy popular, al igual que la configuración estándar. Por ahora se va a crear un archivo ~.eslintrc.json~ para comenzar a ligar el proyecto.



Cree este archivo llamado .eslintrc.json.